#! /bin/sh

### BEGIN INIT INFO
# Provides:          sudo
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:    rmnologin
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Provide limited super user privileges to specific users
# Description: Provide limited super user privileges to specific users.
### END INIT INFO


case "$1" in
  start)
	# make sure privileges don't persist across reboots
	/home/arne/Digilinus/StartDigilinus.sh
	;;
  stop|reload|restart|force-reload|status)
	
	echo "Stop cmd recieved"
	exit 1
	;;
esac

exit 0
